// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcorrmatrix_cpp_
arma::mat rcorrmatrix_cpp_(double alphad, int d, float tol, int maxiter_cg);
RcppExport SEXP _effrcor_rcorrmatrix_cpp_(SEXP alphadSEXP, SEXP dSEXP, SEXP tolSEXP, SEXP maxiter_cgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alphad(alphadSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< float >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter_cg(maxiter_cgSEXP);
    rcpp_result_gen = Rcpp::wrap(rcorrmatrix_cpp_(alphad, d, tol, maxiter_cg));
    return rcpp_result_gen;
END_RCPP
}


static const R_CallMethodDef CallEntries[] = {
    {"_effrcor_rcorrmatrix_cpp_", (DL_FUNC) &_effrcor_rcorrmatrix_cpp_, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_effrcor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
