# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.rcorrmatrix_cpp_ <- function(alphad, d, tol = .0000001, maxiter_cg = 1000L) {
    .Call(`_effrcor_rcorrmatrix_cpp_`, alphad, d, tol, maxiter_cg)
}
